import { CarProps } from "@/types";

export const cars: CarProps[] = [
  {
    city_mpg: 32,
    class: "compact car",
    combination_mpg: 35,
    cylinders: 4,
    displacement: 1.8,
    drive: "fwd",
    fuel_type: "gas",
    highway_mpg: 41,
    make: "toyota",
    model: "corolla",
    transmission: "a",
    year: 2022
  },
  {
    city_mpg: 30,
    class: "compact car",
    combination_mpg: 33,
    cylinders: 4,
    displacement: 1.8,
    drive: "fwd",
    fuel_type: "gas",
    highway_mpg: 38,
    make: "toyota",
    model: "corolla",
    transmission: "m",
    year: 2021
  },
  {
    city_mpg: 28,
    class: "compact car",
    combination_mpg: 31,
    cylinders: 4,
    displacement: 1.8,
    drive: "fwd",
    fuel_type: "gas",
    highway_mpg: 36,
    make: "toyota",
    model: "corolla",
    transmission: "a",
    year: 2020
  },
  {
    city_mpg: 31,
    class: "compact car",
    combination_mpg: 34,
    cylinders: 4,
    displacement: 1.8,
    drive: "fwd",
    fuel_type: "gas",
    highway_mpg: 40,
    make: "toyota",
    model: "corolla",
    transmission: "m",
    year: 2023
  },
  {
    city_mpg: 33,
    class: "compact car",
    combination_mpg: 36,
    cylinders: 4,
    displacement: 2.0,
    drive: "fwd",
    fuel_type: "gas",
    highway_mpg: 42,
    make: "honda",
    model: "civic",
    transmission: "a",
    year: 2023
  },
  {
    city_mpg: 31,
    class: "compact car",
    combination_mpg: 34,
    cylinders: 4,
    displacement: 2.0,
    drive: "fwd",
    fuel_type: "gas",
    highway_mpg: 39,
    make: "honda",
    model: "civic",
    transmission: "m",
    year: 2022
  },
  {
    city_mpg: 26,
    class: "compact luxury car",
    combination_mpg: 30,
    cylinders: 4,
    displacement: 2.0,
    drive: "rwd",
    fuel_type: "gas",
    highway_mpg: 36,
    make: "bmw",
    model: "3 series",
    transmission: "a",
    year: 2023
  },
  {
    city_mpg: 24,
    class: "compact luxury car",
    combination_mpg: 28,
    cylinders: 6,
    displacement: 3.0,
    drive: "awd",
    fuel_type: "gas",
    highway_mpg: 34,
    make: "bmw",
    model: "3 series",
    transmission: "a",
    year: 2022
  },
  {
    city_mpg: 138,
    class: "luxury electric",
    combination_mpg: 126,
    cylinders: 0,
    displacement: 0,
    drive: "rwd",
    fuel_type: "electricity",
    highway_mpg: 115,
    make: "tesla",
    model: "model 3",
    transmission: "a",
    year: 2023
  },
  {
    city_mpg: 134,
    class: "luxury electric",
    combination_mpg: 120,
    cylinders: 0,
    displacement: 0,
    drive: "awd",
    fuel_type: "electricity",
    highway_mpg: 109,
    make: "tesla",
    model: "model 3",
    transmission: "a",
    year: 2022
  },
  {
    city_mpg: 20,
    class: "pickup truck",
    combination_mpg: 24,
    cylinders: 6,
    displacement: 3.5,
    drive: "4wd",
    fuel_type: "gas",
    highway_mpg: 28,
    make: "ford",
    model: "f-150",
    transmission: "a",
    year: 2023
  },
  {
    city_mpg: 18,
    class: "pickup truck",
    combination_mpg: 22,
    cylinders: 8,
    displacement: 5.0,
    drive: "4wd",
    fuel_type: "gas",
    highway_mpg: 26,
    make: "ford",
    model: "f-150",
    transmission: "a",
    year: 2022
  },
  {
    city_mpg: 24,
    class: "luxury sedan",
    combination_mpg: 28,
    cylinders: 4,
    displacement: 2.0,
    drive: "rwd",
    fuel_type: "gas",
    highway_mpg: 34,
    make: "mercedes-benz",
    model: "c-class",
    transmission: "a",
    year: 2023
  },
  {
    city_mpg: 27,
    class: "luxury sedan",
    combination_mpg: 31,
    cylinders: 4,
    displacement: 2.0,
    drive: "awd",
    fuel_type: "gas",
    highway_mpg: 37,
    make: "audi",
    model: "a4",
    transmission: "a",
    year: 2023
  },
  {
    city_mpg: 29,
    class: "compact car",
    combination_mpg: 33,
    cylinders: 4,
    displacement: 1.4,
    drive: "fwd",
    fuel_type: "gas",
    highway_mpg: 39,
    make: "volkswagen",
    model: "golf",
    transmission: "a",
    year: 2022
  },
  {
    city_mpg: 29,
    class: "midsize car",
    combination_mpg: 32,
    cylinders: 4,
    displacement: 1.5,
    drive: "fwd",
    fuel_type: "gas",
    highway_mpg: 36,
    make: "chevrolet",
    model: "malibu",
    transmission: "a",
    year: 2023
  }
];
